#!/usr/bin/env python3
"""DustBunny data generator — the server's own truth about what can be
destroyed profitably.

Modes:
  generate - freeze the lists into DustBunnyData.lua + dustbunny-manifest.tsv
  verify   - re-derive and diff the emitted files

Sources (acore_world, read live each run — Rule 0):
  Disenchant:  item_template.DisenchantID > 0, skill = RequiredDisenchantSkill
               (-1 -> 0). Legendary+ (Quality >= 5) EXCLUDED AT GENERATION —
               the Thunderfury clause enforced in the data itself (ruling C
               2026-07-22: only Legendary protected; epics are fair game).
  Milling:     Flags & 0x20000000 (ITEM_FLAG_IS_MILLABLE, ItemTemplate.h:176)
               INTERSECTED with milling_loot_template keys.
  Prospecting: Flags & 0x00040000 (ITEM_FLAG_IS_PROSPECTABLE, :165)
               INTERSECTED with prospecting_loot_template keys.
               The flag alone lies: 5 Powder curios (24190/24234/24235/
               24242/24243) are flagged but have no loot — prospectable
               into the void. Flag AND loot required; ghosts reported.
  Mill/prospect skill = the herb/ore row's RequiredSkillRank (the server's
  gate per SpellEffects.cpp:5540/5565 + CheckItems).
"""
import os
import subprocess
import sys

DEV_DIR = os.path.dirname(os.path.abspath(__file__))          # dev/ (tracked since 1.1.0)
OUT_DIR = os.path.dirname(DEV_DIR)                               # the addon root
LUA_OUT = os.path.join(OUT_DIR, "DustBunnyData.lua")
MANIFEST = os.path.join(DEV_DIR, "dustbunny-manifest.tsv")
CONF = "/media/linuxdata/WOW_Private/playerbots_server/etc/worldserver.conf"


def creds():
    with open(CONF) as f:
        for line in f:
            if line.startswith("WorldDatabaseInfo"):
                info = line.split('"')[1].split(";")
                return info  # host, port, user, pass, db
    sys.exit("WorldDatabaseInfo not found")


def q(sql):
    host, port, user, pw, db = creds()
    env = dict(os.environ, MYSQL_PWD=pw)
    out = subprocess.run(
        ["mysql", "-h", host, "-P", port, "-u", user, db, "-N", "-e", sql],
        capture_output=True, text=True, env=env, check=True)
    return [row.split("\t") for row in out.stdout.splitlines()]


def load():
    de = {int(e): max(0, int(s)) for e, s in q(
        "SELECT entry, RequiredDisenchantSkill FROM item_template "
        "WHERE DisenchantID > 0 AND Quality < 5")}
    legendary_deids = int(q(
        "SELECT COUNT(*) FROM item_template "
        "WHERE DisenchantID > 0 AND Quality >= 5")[0][0])

    mill = {int(e): int(r) for e, r in q(
        "SELECT entry, RequiredSkillRank FROM item_template "
        "WHERE Flags & 0x20000000 "
        "AND entry IN (SELECT DISTINCT Entry FROM milling_loot_template)")}
    prospect = {int(e): int(r) for e, r in q(
        "SELECT entry, RequiredSkillRank FROM item_template "
        "WHERE Flags & 0x40000 "
        "AND entry IN (SELECT DISTINCT Entry FROM prospecting_loot_template)")}

    ghosts = q(
        "SELECT entry, name FROM item_template WHERE "
        "(Flags & 0x20000000 AND entry NOT IN "
        " (SELECT DISTINCT Entry FROM milling_loot_template)) OR "
        "(Flags & 0x40000 AND entry NOT IN "
        " (SELECT DISTINCT Entry FROM prospecting_loot_template)) "
        "ORDER BY entry")
    return de, mill, prospect, ghosts, legendary_deids


def emit_map(name, data):
    lines = [f"    {name} = {{"]
    items = sorted(data.items())
    for i in range(0, len(items), 10):
        chunk = items[i:i + 10]
        lines.append("        " + " ".join(f"[{e}]={s}," for e, s in chunk))
    lines.append("    },")
    return lines


def emit(de, mill, prospect):
    L = ["-- DustBunnyData.lua -- GENERATED by gen_dustbunny.py; do not hand-edit.",
         "-- Truth source: acore_world item_template + milling/prospecting loot",
         "-- tables. Values are required skill (Enchanting / Inscription /",
         "-- Jewelcrafting). Legendary+ items are ABSENT BY GENERATION.",
         "DustBunny_Data = {"]
    L += emit_map("disenchant", de)
    L += emit_map("mill", mill)
    L += emit_map("prospect", prospect)
    L.append("}")
    return "\n".join(L) + "\n"


def manifest(de, mill, prospect, ghosts, legendary_deids):
    L = ["kind\tcount/detail"]
    L.append(f"disenchantable\t{len(de)}")
    L.append(f"legendary_plus_excluded_at_gen\t{legendary_deids}")
    L.append(f"millable\t{len(mill)}")
    L.append(f"prospectable\t{len(prospect)}")
    for e, n in ghosts:
        L.append(f"ghost_flagged_no_loot\t{e} {n}")
    return "\n".join(L) + "\n"


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else ""
    if mode not in ("generate", "verify"):
        sys.exit("usage: gen_dustbunny.py generate|verify")
    de, mill, prospect, ghosts, leg = load()
    lua, man = emit(de, mill, prospect), manifest(de, mill, prospect, ghosts, leg)
    if mode == "generate":
        open(LUA_OUT, "w").write(lua)
        open(MANIFEST, "w").write(man)
        print(f"disenchant {len(de)} | mill {len(mill)} | prospect {len(prospect)}"
              f" | ghosts {len(ghosts)} | legendary+ excluded {leg}")
        print(f"wrote {LUA_OUT}\nwrote {MANIFEST}")
    else:
        ok = True
        for path, want in ((LUA_OUT, lua), (MANIFEST, man)):
            have = open(path).read() if os.path.exists(path) else None
            if have != want:
                ok = False
                print(f"DEVIATION: {path}")
        print("verify:", "PASS" if ok else "FAIL")
        sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
